### ISSUE TITLE
请问一下build出错的问题？

### ISSUE THREAD

**Issue by yourenA** [Eleme-IMF/dodo#13]
build的过程中报下面的错误
...
:ele-react-native-location:compileReleaseJavaWithJavac
:ele-react-native-location:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
ע: E:\react-native\ReactNativePlatform\node_modules\ele-react-native-location\android\src\main\java\me\ele\dodo\AMapLocationReactModule.javaʹ▒û򸲸▒▒▒▒ѹ▒ʱ▒▒ API▒▒
ע:
...

然后在最后报这个错误，对Java不了解，使引入包的错误吗？
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
E:\react-native\ReactNativePlatform\android\app\src\main\java\com\reactnativeplatform\MainApplication.java:12: 错误: 找 不到符号
import me.ele.dodo.AMapLocationRecatPackage;
                         ^
  符号:   类 AMapLocationRecatPackage
  位置: 程序包 me.ele.dodo
E:\react-native\ReactNativePlatform\android\app\src\main\java\com\reactnativeplatform\MainApplication.java:31: 错误: 找 不到符号
          new AMapLocationReactPackage()
                  ^
  符号: 类 AMapLocationReactPackage
2 个错误
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

下面这段错误第一个箭头是指向dodo后面的点，第二个箭头是指向AMapLocationReactPackage第一个字母A

**Comment by yourenA** [comment]
我的错，在import的时候AMapLocationReactPackage打错了

**Comment by Holdge** [comment]
@yourenA happy hacking

**Comment by yourenA** [comment]
请问一下你对react-native-smart-amap了解吗？我这也有一个issue是关于build出错的，可以帮我看一下吗？看一下导入包的地址是不是这个 import com.reactnativecomponent.amaplocation.RCTAMapPackage;
https://github.com/react-native-component/react-native-smart-amap/issues/14

**Comment by Holdge** [comment]
@yourenA 还是问一下 react-native-smart-amap 作者吧

**Comment by yourenA** [comment]
好的，谢谢
