### ISSUE TITLE
iOS引入#import <AMapFoundationKit/AMapFoundationKit.h>报错

### ISSUE THREAD

**Issue by BBBOND** [Eleme-IMF/dodo#14]
错误内容
'AMapFoundationKit/AMapFoundationKit.h' file not found

**Comment by Holdge** [comment]
@galaxycoder 高老师😜

**Comment by nukc** [comment]
在 Xcode 中打开，把 ```AMapFoundationKit.framework``` 和 ```AMapLocationKit.framework``` 添加(可拖拽)到 iOS 主目录下的 Frameworks 中，选择 copy items if needed, create groups

**Comment by nukc** [comment]
REMAD.md 中
Android 的第一二步配置（gradle）和 iOS 配置第一步 (Library)
可使用 ```react-native link ele-react-native-location``` 进行自动配置，省去手动配置

**Comment by Holdge** [comment]
@nukc 多谢。
