### ISSUE TITLE
请问一下，这个库会继续维护吗？

### ISSUE THREAD

**Issue by MirGhojam** [Eleme-IMF/dodo#19]

**Comment by Holdge** [comment]
@MirGhojam 会呀，你遇到什么了吗

**Comment by MirGhojam** [comment]
@KevinOfNeu 没有，我的App也需要定位，用的是 react-native-smart-amap  这个库，因为审核不通过结果就等了一个月，吃了不少苦头。所以才提问的 https://github.com/react-native-component/react-native-smart-amap
