### ISSUE TITLE
刚接触react-native，请教 编译时提示 错误: 找不到符号 如何解决？

### ISSUE THREAD

**Issue by jfcai** [Eleme-IMF/dodo#6]
MainApplication.java:30: 错误: 找不到符号
          new AMapLocationReactPackage()

**Comment by Holdge** [comment]
@jfcai  感觉你npm install 完毕后，没有按照README配置gradle。

**Comment by jfcai** [comment]
发现问题了，MainApplication.java 需要import me.ele.dodo.AMapLocationRecatPackage;
在你的README中并未提到。

**Comment by Holdge** [comment]
ok，我的锅，个人认为是common sense的东西。
