### ISSUE TITLE
Android 通过BackAndroid退出App之后再次进去App定位,不会触发listener.

### ISSUE THREAD

**Issue by AdamChrist** [Eleme-IMF/dodo#9]
react-native 版本: 0.41.2
Android中的onLocationChanged也不会触发
具体原因不明,一定要杀掉App进程,再次进去才可以.

**Comment by Holdge** [comment]
@AdamChrist Android 设备型号，系统版本等可以提供一下吗？我这里复现一下

**Comment by AdamChrist** [comment]
@KevinOfNeu 小米Note2 MIUI8 Android 5.0.2

**Comment by AdamChrist** [comment]
@KevinOfNeu 又用华为的荣耀6 EMUI4 Android 6.0 测试了一下..还是一样的问题.

**Comment by Holdge** [comment]
@AdamChrist [触发location Change 的代码](https://github.com/Eleme-IMF/dodo/blob/master/android/src/main/java/me/ele/dodo/AMapLocationReactModule.java#L152)，然后你贴一下你的代码我看下，我这边暂时不能复现，我可以先帮你看下是否是用法上的问题

**Comment by AdamChrist** [comment]
@KevinOfNeu  我最近尝试使用react-navigation,所以正好写在这个Demo中.高德的Key还是用的之前的App的..所以得不到数据,但是还是能看到效果..使用后退键退出之后在进入那个Location的界面,不会触发listener.
https://github.com/AdamChrist/ReactNavigationDemo
在目录中的Link to Location
非常感谢.

**Comment by Holdge** [comment]
@AdamChrist 我看了你代码，有一处可能导致此问题，[代码](https://github.com/AdamChrist/ReactNavigationDemo/blob/master/js/Location.js#L32)，`onceLocation: false, // 是否只定位一次`，设置为 true 的话定位一次后，就结束了。改成 false 试试，我这边 HOME 到后台，console 可以持续输出 `{"errorInfo":"KEY错误 请到http://lbs.amap.com/api/android-location-sdk/abouterrorcode/查看错误码说明.","errorCode":7}`

**Comment by AdamChrist** [comment]
@KevinOfNeu 
https://youtu.be/mW3TfM5hkC4
我已经从windows换到了mac环境.location的参数已经改了.问题依旧,囧....
详情可以看下视频

**Comment by Holdge** [comment]
@AdamChrist #10 此问题已修复， 可以使用 0.2.1 这个版本。
